name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - uat
          - beta

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set BASEURL
      id: set_url
      run: |
        ENVIRONMENT="${{ github.event.inputs.environment || 'dev' }}"
        if [[ "$ENVIRONMENT" == "dev" ]]; then
          echo "BASEURL=https://dev-drivebc.apps.gold.devops.gov.bc.ca" >> $GITHUB_ENV
        elif [[ "$ENVIRONMENT" == "test" ]]; then
          echo "BASEURL=https://test-drivebc.apps.gold.devops.gov.bc.ca" >> $GITHUB_ENV
        elif [[ "$ENVIRONMENT" == "uat" ]]; then
          echo "BASEURL=https://uat-drivebc.apps.gold.devops.gov.bc.ca" >> $GITHUB_ENV
        elif [[ "$ENVIRONMENT" == "beta" ]]; then
          echo "BASEURL=https://beta.drivebc.ca" >> $GITHUB_ENV
        fi
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASEURL: ${{ env.BASEURL }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
