name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - uat
          - beta

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Set BASEURL
      id: set_url
      env:
        ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
      run: |
        echo $GITHUB_ENV
        if [[ "${{ env.ENVIRONMENT }}" == "dev" ]]; then
          echo "::set-output name=baseurl::https://dev-drivebc.apps.gold.devops.gov.bc.ca"
        elif [[ "${{ env.ENVIRONMENT }}" == "test" ]]; then
          echo "::set-output name=baseurl::https://test-drivebc.apps.gold.devops.gov.bc.ca"
        elif [[ "${{ env.ENVIRONMENT }}" == "uat" ]]; then
          echo "::set-output name=baseurl::https://uat-drivebc.apps.gold.devops.gov.bc.ca"
        elif [[ "${{ env.ENVIRONMENT }}" == "beta" ]]; then
          echo "::set-output name=baseurl::https://beta.drivebc.ca"
        fi
    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASEURL: ${{ steps.set_url.outputs.baseurl }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
